version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    image: kyoheius/rails_slides_web:0.0.2
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails_slides
      - bundle:/usr/local/bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  pgdata:
    driver: local
  bundle: null
